# add_llm_failure_enum
# Revision ID: 151b631eba3d
# Revises: a1b2c3d4e5f6
# Create Date: 2026-08-21 06:46:04.531152

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '151b631eba3d'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'LLM_EXPLANATION_FAILED'")
    op.drop_index('uq_payment_events_external_id', table_name='payment_events')
    op.create_unique_constraint(
        'uq_payment_events_external_id',
        'payment_events',
        ['external_event_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_events_external_id', 'payment_events', type_='unique')
    op.create_index(
        'uq_payment_events_external_id',
        'payment_events',
        ['external_event_id'],
        unique=True,
    )
    # ### end Alembic commands ###
